version: '2.4'

services:

  # database for filament_manager plugin (comment if not needed, you may also remove this plugin from printers dockerfiles)
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      net:
        ipv4_address: 172.18.0.2
    restart: always
    environment:
      POSTGRES_USER: octoprint
      POSTGRES_PASSWORD: octoprint
      POSTGRES_DB: octoprint_filamentmanager
    ports:
      - 5432:5432

  # database administrator on port 4000 for filament_manager (comment if not needed)
  dbadmin:
    image: adminer
    environment:
      - ADMINER_DESIGN='nette'
      - ADMINER_DEFAULT_SERVER=db
    networks:
      net:
        ipv4_address: 172.18.0.3    
    restart: always
    ports:
      - 4000:8080

  # printer #1 on port 3001
  prusai3-00:
    build: octoprint/prusai3
    image: octoprint/prusai3
    volumes:
      - prusai3-00-data:/octoprint
    devices:
      - /dev/hub01:/dev/ttyUSB
     # - /dev/hub02_cam:/dev/video0
    environment:
      - ENABLE_MJPG_STREAMER=false
     # - MJPG_STREAMER_INPUT=-n -f 30 -r 640x480
    networks:
      net:
        ipv4_address: 172.18.0.11
    restart: always
    ports:
      - 3001:80

  # printer #2 on port 3002
  prusai3-01:
    build: octoprint/prusai3
    image: octoprint/prusai3
    volumes:
      - prusai3-01-data:/octoprint
    devices:
      - /dev/hub03:/dev/ttyUSB
     # - /dev/hub04_cam:/dev/video0
    environment:
      - ENABLE_MJPG_STREAMER=false
     # - MJPG_STREAMER_INPUT=-n -f 30 -r 640x480
    networks:
      net:
        ipv4_address: 172.18.0.12
    restart: always
    ports:
      - 3002:80


networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

volumes:
  db-data:
    driver: local
  prusai3-00-data:
    driver: local
  prusai3-01-data:
    driver: local
    